# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grammers/arrowhead/fork_client-cpp/client-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grammers/arrowhead/fork_client-cpp/client-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grammers/arrowhead/fork_client-cpp/client-cpp/CMakeFiles /home/grammers/arrowhead/fork_client-cpp/client-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grammers/arrowhead/fork_client-cpp/client-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arrowhead_cpp

# Build rule for target.
arrowhead_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arrowhead_cpp
.PHONY : arrowhead_cpp

# fast build rule for target.
arrowhead_cpp/fast:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/build
.PHONY : arrowhead_cpp/fast

src/ArrowheadDataExt.o: src/ArrowheadDataExt.cpp.o

.PHONY : src/ArrowheadDataExt.o

# target to build an object file
src/ArrowheadDataExt.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/ArrowheadDataExt.cpp.o
.PHONY : src/ArrowheadDataExt.cpp.o

src/ArrowheadDataExt.i: src/ArrowheadDataExt.cpp.i

.PHONY : src/ArrowheadDataExt.i

# target to preprocess a source file
src/ArrowheadDataExt.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/ArrowheadDataExt.cpp.i
.PHONY : src/ArrowheadDataExt.cpp.i

src/ArrowheadDataExt.s: src/ArrowheadDataExt.cpp.s

.PHONY : src/ArrowheadDataExt.s

# target to generate assembly for a file
src/ArrowheadDataExt.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/ArrowheadDataExt.cpp.s
.PHONY : src/ArrowheadDataExt.cpp.s

src/Consumer.o: src/Consumer.cpp.o

.PHONY : src/Consumer.o

# target to build an object file
src/Consumer.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Consumer.cpp.o
.PHONY : src/Consumer.cpp.o

src/Consumer.i: src/Consumer.cpp.i

.PHONY : src/Consumer.i

# target to preprocess a source file
src/Consumer.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Consumer.cpp.i
.PHONY : src/Consumer.cpp.i

src/Consumer.s: src/Consumer.cpp.s

.PHONY : src/Consumer.s

# target to generate assembly for a file
src/Consumer.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Consumer.cpp.s
.PHONY : src/Consumer.cpp.s

src/Interface/ApplicationServiceInterface.o: src/Interface/ApplicationServiceInterface.cpp.o

.PHONY : src/Interface/ApplicationServiceInterface.o

# target to build an object file
src/Interface/ApplicationServiceInterface.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ApplicationServiceInterface.cpp.o
.PHONY : src/Interface/ApplicationServiceInterface.cpp.o

src/Interface/ApplicationServiceInterface.i: src/Interface/ApplicationServiceInterface.cpp.i

.PHONY : src/Interface/ApplicationServiceInterface.i

# target to preprocess a source file
src/Interface/ApplicationServiceInterface.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ApplicationServiceInterface.cpp.i
.PHONY : src/Interface/ApplicationServiceInterface.cpp.i

src/Interface/ApplicationServiceInterface.s: src/Interface/ApplicationServiceInterface.cpp.s

.PHONY : src/Interface/ApplicationServiceInterface.s

# target to generate assembly for a file
src/Interface/ApplicationServiceInterface.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ApplicationServiceInterface.cpp.s
.PHONY : src/Interface/ApplicationServiceInterface.cpp.s

src/Interface/HttpHandler.o: src/Interface/HttpHandler.cpp.o

.PHONY : src/Interface/HttpHandler.o

# target to build an object file
src/Interface/HttpHandler.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/HttpHandler.cpp.o
.PHONY : src/Interface/HttpHandler.cpp.o

src/Interface/HttpHandler.i: src/Interface/HttpHandler.cpp.i

.PHONY : src/Interface/HttpHandler.i

# target to preprocess a source file
src/Interface/HttpHandler.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/HttpHandler.cpp.i
.PHONY : src/Interface/HttpHandler.cpp.i

src/Interface/HttpHandler.s: src/Interface/HttpHandler.cpp.s

.PHONY : src/Interface/HttpHandler.s

# target to generate assembly for a file
src/Interface/HttpHandler.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/HttpHandler.cpp.s
.PHONY : src/Interface/HttpHandler.cpp.s

src/Interface/HttpsHandler.o: src/Interface/HttpsHandler.cpp.o

.PHONY : src/Interface/HttpsHandler.o

# target to build an object file
src/Interface/HttpsHandler.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/HttpsHandler.cpp.o
.PHONY : src/Interface/HttpsHandler.cpp.o

src/Interface/HttpsHandler.i: src/Interface/HttpsHandler.cpp.i

.PHONY : src/Interface/HttpsHandler.i

# target to preprocess a source file
src/Interface/HttpsHandler.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/HttpsHandler.cpp.i
.PHONY : src/Interface/HttpsHandler.cpp.i

src/Interface/HttpsHandler.s: src/Interface/HttpsHandler.cpp.s

.PHONY : src/Interface/HttpsHandler.s

# target to generate assembly for a file
src/Interface/HttpsHandler.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/HttpsHandler.cpp.s
.PHONY : src/Interface/HttpsHandler.cpp.s

src/Interface/OrchestratorInterface.o: src/Interface/OrchestratorInterface.cpp.o

.PHONY : src/Interface/OrchestratorInterface.o

# target to build an object file
src/Interface/OrchestratorInterface.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/OrchestratorInterface.cpp.o
.PHONY : src/Interface/OrchestratorInterface.cpp.o

src/Interface/OrchestratorInterface.i: src/Interface/OrchestratorInterface.cpp.i

.PHONY : src/Interface/OrchestratorInterface.i

# target to preprocess a source file
src/Interface/OrchestratorInterface.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/OrchestratorInterface.cpp.i
.PHONY : src/Interface/OrchestratorInterface.cpp.i

src/Interface/OrchestratorInterface.s: src/Interface/OrchestratorInterface.cpp.s

.PHONY : src/Interface/OrchestratorInterface.s

# target to generate assembly for a file
src/Interface/OrchestratorInterface.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/OrchestratorInterface.cpp.s
.PHONY : src/Interface/OrchestratorInterface.cpp.s

src/Interface/ini/dictionary.o: src/Interface/ini/dictionary.c.o

.PHONY : src/Interface/ini/dictionary.o

# target to build an object file
src/Interface/ini/dictionary.c.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ini/dictionary.c.o
.PHONY : src/Interface/ini/dictionary.c.o

src/Interface/ini/dictionary.i: src/Interface/ini/dictionary.c.i

.PHONY : src/Interface/ini/dictionary.i

# target to preprocess a source file
src/Interface/ini/dictionary.c.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ini/dictionary.c.i
.PHONY : src/Interface/ini/dictionary.c.i

src/Interface/ini/dictionary.s: src/Interface/ini/dictionary.c.s

.PHONY : src/Interface/ini/dictionary.s

# target to generate assembly for a file
src/Interface/ini/dictionary.c.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ini/dictionary.c.s
.PHONY : src/Interface/ini/dictionary.c.s

src/Interface/ini/iniparser.o: src/Interface/ini/iniparser.c.o

.PHONY : src/Interface/ini/iniparser.o

# target to build an object file
src/Interface/ini/iniparser.c.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ini/iniparser.c.o
.PHONY : src/Interface/ini/iniparser.c.o

src/Interface/ini/iniparser.i: src/Interface/ini/iniparser.c.i

.PHONY : src/Interface/ini/iniparser.i

# target to preprocess a source file
src/Interface/ini/iniparser.c.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ini/iniparser.c.i
.PHONY : src/Interface/ini/iniparser.c.i

src/Interface/ini/iniparser.s: src/Interface/ini/iniparser.c.s

.PHONY : src/Interface/ini/iniparser.s

# target to generate assembly for a file
src/Interface/ini/iniparser.c.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Interface/ini/iniparser.c.s
.PHONY : src/Interface/ini/iniparser.c.s

src/Provider.o: src/Provider.cpp.o

.PHONY : src/Provider.o

# target to build an object file
src/Provider.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Provider.cpp.o
.PHONY : src/Provider.cpp.o

src/Provider.i: src/Provider.cpp.i

.PHONY : src/Provider.i

# target to preprocess a source file
src/Provider.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Provider.cpp.i
.PHONY : src/Provider.cpp.i

src/Provider.s: src/Provider.cpp.s

.PHONY : src/Provider.s

# target to generate assembly for a file
src/Provider.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Provider.cpp.s
.PHONY : src/Provider.cpp.s

src/Publisher.o: src/Publisher.cpp.o

.PHONY : src/Publisher.o

# target to build an object file
src/Publisher.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Publisher.cpp.o
.PHONY : src/Publisher.cpp.o

src/Publisher.i: src/Publisher.cpp.i

.PHONY : src/Publisher.i

# target to preprocess a source file
src/Publisher.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Publisher.cpp.i
.PHONY : src/Publisher.cpp.i

src/Publisher.s: src/Publisher.cpp.s

.PHONY : src/Publisher.s

# target to generate assembly for a file
src/Publisher.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Publisher.cpp.s
.PHONY : src/Publisher.cpp.s

src/Security/RSASecurity.o: src/Security/RSASecurity.cpp.o

.PHONY : src/Security/RSASecurity.o

# target to build an object file
src/Security/RSASecurity.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Security/RSASecurity.cpp.o
.PHONY : src/Security/RSASecurity.cpp.o

src/Security/RSASecurity.i: src/Security/RSASecurity.cpp.i

.PHONY : src/Security/RSASecurity.i

# target to preprocess a source file
src/Security/RSASecurity.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Security/RSASecurity.cpp.i
.PHONY : src/Security/RSASecurity.cpp.i

src/Security/RSASecurity.s: src/Security/RSASecurity.cpp.s

.PHONY : src/Security/RSASecurity.s

# target to generate assembly for a file
src/Security/RSASecurity.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Security/RSASecurity.cpp.s
.PHONY : src/Security/RSASecurity.cpp.s

src/Security/base64.o: src/Security/base64.cpp.o

.PHONY : src/Security/base64.o

# target to build an object file
src/Security/base64.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Security/base64.cpp.o
.PHONY : src/Security/base64.cpp.o

src/Security/base64.i: src/Security/base64.cpp.i

.PHONY : src/Security/base64.i

# target to preprocess a source file
src/Security/base64.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Security/base64.cpp.i
.PHONY : src/Security/base64.cpp.i

src/Security/base64.s: src/Security/base64.cpp.s

.PHONY : src/Security/base64.s

# target to generate assembly for a file
src/Security/base64.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Security/base64.cpp.s
.PHONY : src/Security/base64.cpp.s

src/Subscriber.o: src/Subscriber.cpp.o

.PHONY : src/Subscriber.o

# target to build an object file
src/Subscriber.cpp.o:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Subscriber.cpp.o
.PHONY : src/Subscriber.cpp.o

src/Subscriber.i: src/Subscriber.cpp.i

.PHONY : src/Subscriber.i

# target to preprocess a source file
src/Subscriber.cpp.i:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Subscriber.cpp.i
.PHONY : src/Subscriber.cpp.i

src/Subscriber.s: src/Subscriber.cpp.s

.PHONY : src/Subscriber.s

# target to generate assembly for a file
src/Subscriber.cpp.s:
	$(MAKE) -f CMakeFiles/arrowhead_cpp.dir/build.make CMakeFiles/arrowhead_cpp.dir/src/Subscriber.cpp.s
.PHONY : src/Subscriber.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... arrowhead_cpp"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... src/ArrowheadDataExt.o"
	@echo "... src/ArrowheadDataExt.i"
	@echo "... src/ArrowheadDataExt.s"
	@echo "... src/Consumer.o"
	@echo "... src/Consumer.i"
	@echo "... src/Consumer.s"
	@echo "... src/Interface/ApplicationServiceInterface.o"
	@echo "... src/Interface/ApplicationServiceInterface.i"
	@echo "... src/Interface/ApplicationServiceInterface.s"
	@echo "... src/Interface/HttpHandler.o"
	@echo "... src/Interface/HttpHandler.i"
	@echo "... src/Interface/HttpHandler.s"
	@echo "... src/Interface/HttpsHandler.o"
	@echo "... src/Interface/HttpsHandler.i"
	@echo "... src/Interface/HttpsHandler.s"
	@echo "... src/Interface/OrchestratorInterface.o"
	@echo "... src/Interface/OrchestratorInterface.i"
	@echo "... src/Interface/OrchestratorInterface.s"
	@echo "... src/Interface/ini/dictionary.o"
	@echo "... src/Interface/ini/dictionary.i"
	@echo "... src/Interface/ini/dictionary.s"
	@echo "... src/Interface/ini/iniparser.o"
	@echo "... src/Interface/ini/iniparser.i"
	@echo "... src/Interface/ini/iniparser.s"
	@echo "... src/Provider.o"
	@echo "... src/Provider.i"
	@echo "... src/Provider.s"
	@echo "... src/Publisher.o"
	@echo "... src/Publisher.i"
	@echo "... src/Publisher.s"
	@echo "... src/Security/RSASecurity.o"
	@echo "... src/Security/RSASecurity.i"
	@echo "... src/Security/RSASecurity.s"
	@echo "... src/Security/base64.o"
	@echo "... src/Security/base64.i"
	@echo "... src/Security/base64.s"
	@echo "... src/Subscriber.o"
	@echo "... src/Subscriber.i"
	@echo "... src/Subscriber.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

